"""Avatar, genre, and common-term dictionaries for auto-tagging and autocomplete.

Word list maps lowercase tokens to canonical tag names.
Tag hierarchy defines parent-child implication rules.
"""

from __future__ import annotations

# ── Top Avatars (by community popularity, from marketplace stats) ──
# Ordered by number of compatible items listed on the marketplace.
# 240 avatars in descending popularity order.
TOP_AVATARS: list[str] = [
    "Kipfel", "Shinano", "Manuka", "Milltina", "rurune", "mamehinata", "Chocolat",
    "Shinra", "Selestia", "Kikyo", "Minase", "Sio", "Milfy", "Rinasciita", "Komano",
    "Mafuyu", "Eku", "Chiffon", "Karin", "Lumina", "Marycia", "mao", "Moe",
    "Lasyusha", "Ichigo", "Rusk", "Maya", "Mizuki", "Hakka", "Airi", "Zome",
    "Lapwing", "Deltaflair", "Lime", "Kanata", "Rindo", "Bokusei", "Hanka", "Nagi",
    "Alué", "Ghost Fox Sister", "RadDollV2", "usasaki", "Ash", "Kuuta", "nemesis",
    "Nanase Noir", "ELusion", "Felis", "Yoll", "Miminoko", "Platinum", "Sapphy",
    "Nayu", "Sophina", "Wolferia", "New NecoMaid", "U (QuQu)", "Anri", "Shiratsume",
    "ririka", "Mishe", "Grus", "Fiona", "Kokoa", "Liloumois", "minahoshi", "Mint",
    "Lazuli", "Koyuki", "Shizuku-san", "Soraha", "KALNE", "HAOLAN", "Maki", "Shuan",
    "Flare", "Low-Poly Kon (Archive 2019)", "Leefa", "Iris", "Kaya", "Lunalitt",
    "Scented", "patoto", "Imeris", "Cian", "Milk", "inuinu", "Leeme & Reeva",
    "Chalo", "meiyun", "Lzebul", "Anon", "Kyoko", "Binah", "Merino", "CyberCat2.0",
    "Velle", "Yugi & Miyo", "Tolass & Wedge", "Azuki", "Nagiya Ruri", "Kyubi",
    "Anomea", "INABA", "Nemo", "Eyo", "Kuronatsu", "RearAlice", "Mururu", "Mulicia",
    "Hatsune Miku", "Cornet", "Hamster", "Foshunia", "Kirise", "Tonnerre", "Aldina",
    "Adolescent U", "Mariel", "LilLeo", "Rize", "Sue", "Ciel (Regular)", "Munkki",
    "Menno", "mashu", "haishima", "Puma the Puma", "Snow Elf Lady", "Makina",
    "Satalina Maid", "Kosame", "Nanodevi", "Emmelie", "Sephira", "Toah", "Darjelling",
    "LETHALFREET", "Gimozard", "Lucifer", "UltimateKissMa", "Mochikichi & Komochi",
    "Noy", "Isanai Nuku", "Sipilka", "Peke (QuQu)", "Beryl", "Chimaco Tribe", "Alu",
    "Nozomi", "Milk & Sugar", "Senneko", "Marshmellow", "Clara", "Retinia", "Kohaku",
    "Sii & Phi", "Shayna", "Intānetto no Pomae", "Pomemaru & Kopomemaru", "YUGIRI",
    "GELAS", "uomaru", "Ururu", "Moko", "nyago", "Sairou", "Wolfram", "Pon & Chune",
    "MUMUS", "Celeate", "Shiratori", "Medical Center Staff", "Fufu", "SvartLilja",
    "Marumaru", "Rei", "Julius", "Sanatia", "Lyphos", "Uruki", "Helvetica",
    "Lena Cocktail", "Saneko", "Nekoyama Nae", "Honoka", "Qunyan", "RUGINEA",
    "Kyalóng", "Kalkia", "Quish", "Noiz", "Inaba Kaya", "patanyako", "Amagi", "Ilio",
    "Seiran", "Runa", "Rufina", "Nix", "Nenmir", "Mophira", "Mia", "Lucife", "SHRI",
    "Uzuruha", "Kisha", "suzuhana", "Rabbit Hole Miku", "Perula", "Tycho", "Fluctua",
    "Perfect Maid Mellotron", "TubeRose", "ninya", "Hina", "Xena", "TUNER", "Maneko",
    "Yoru", "Shinonome", "Shimoe Koharu", "Danzai", "Rainy", "Rushina", "Eve",
    "Machi", "Sirius", "SOKA", "Ryuon", "Yuki", "Snow White Angel", "Runya",
    "pochimaru", "Tsubaki", "Stier", "Luruleah", "Ukon Second Type", "Cyanos",
]

# Japanese avatar name → canonical English tag name
JP_AVATAR_TO_EN: dict[str, str] = {
    "キプフェル": "Kipfel", "きぷふぇる": "Kipfel",
    "ルルネ": "Rurune", "るるね": "Rurune",
    "まめひなた": "Mamehinata", "マメヒナタ": "Mamehinata",
    "まめふれんず": "Mamehinata", "マメフレンズ": "Mamehinata",
    "mamefriends": "Mamehinata", "mame_friends": "Mamehinata",
    "マヌカ": "Manuka", "まぬか": "Manuka",
    "ショコラ": "Chocolat", "しょこら": "Chocolat",
    "ちょこら": "Chocolat", "チョコラ": "Chocolat",
    "みみのこ": "Miminoko", "ミミノコ": "Miminoko",
    "ゆうこ": "Yuko", "ユウコ": "Yuko", "yuuko": "Yuko",
    "まお": "Mao", "マオ": "Mao",
    "シフォン": "Chiffon", "しふぉん": "Chiffon",
    "桔梗": "Kikyo", "キキョウ": "Kikyo", "ききょう": "Kikyo",
    "ラスク": "Rusk", "らすく": "Rusk",
    "セレスティア": "Selestia", "せれすてぃあ": "Selestia",
    "ミント": "Mint", "みんと": "Mint",
    "リリウム": "Lillium", "りりうむ": "Lillium",
    "ヤヨイ": "Yayoi", "やよい": "Yayoi",
    "モエ": "Moe", "もえ": "Moe",
    "フォクシー": "Foxy", "ふぉくしー": "Foxy",
    "レックス": "Rex", "れっくす": "Rex",
    "ずんだもん": "Zundamon", "ズンダモン": "Zundamon",
    "シバ": "Shiba", "しば": "Shiba",
    "ライス": "Rice", "らいす": "Rice",
    "シナモン": "Cinnamon", "しなもん": "Cinnamon",
    "メープル": "Maple", "めーぷる": "Maple",
    "マヤ": "Maya", "まや": "Maya",
    "アメリア": "Amelia", "あめりあ": "Amelia",
    "リンド": "Rindo", "りんど": "Rindo",
    "ツムギ": "Tsumugi", "つむぎ": "Tsumugi",
    "コムギ": "Komugi", "こむぎ": "Komugi",
    "ライム": "Lime", "らいむ": "Lime",
    "アオイ": "Aoi", "あおい": "Aoi",
    "コハク": "Kohaku", "こはく": "Kohaku",
    "スズ": "Suzu", "すず": "Suzu",
    "ニャー": "Nyah", "にゃー": "Nyah",
    "トロリ": "Torori", "とろり": "Torori",
    "セシル": "Cecil", "せしる": "Cecil",
    "ミリー": "Milly", "みりー": "Milly",
    "イロハ": "Iroha", "いろは": "Iroha",
    "ナナチ": "Nanachi", "ななち": "Nanachi",
    "クロネコ": "Kuroneko", "くろねこ": "Kuroneko",
    "ルルミ": "Rurumi", "るるみ": "Rurumi",
    "モモ": "Momo", "もも": "Momo",
    "ユイ": "Yui", "ゆい": "Yui",
    "ステラ": "Stella", "すてら": "Stella",
    "ミオ": "Mio", "みお": "Mio",
    "ヒヨリ": "Hiyori", "ひより": "Hiyori",
    "カンナ": "Kanna", "かんな": "Kanna",
    "シンラ": "Shinra", "しんら": "Shinra",
    "アリア": "Aria", "ありあ": "Aria",
    "リリス": "Lilith", "りりす": "Lilith",
    "ナギサ": "Nagisa", "なぎさ": "Nagisa",
}

# ── Genre/category terms ───────────────────────────
GENRE_TERMS: list[str] = [
    "Avatar Base", "Outfit", "Accessory", "Hairstyle", "Texture",
    "Shader", "Animation", "Gesture", "Expression", "Emote",
    "Prop", "Weapon", "Wings", "Tail", "Ears",
    "Horns", "Tattoo", "Makeup", "Skin", "Eyes",
    "Eyebrows", "Lashes", "Lipstick", "Blush", "Freckles",
    "Scar", "Muscle", "Slim", "Chibi", "Kemono",
    "Furry", "Neko", "Inumimi", "Kitsune", "Elf",
    "Maid", "School", "Military", "Cyberpunk", "Fantasy",
    "Gothic", "Lolita", "Kimono", "Yukata", "Casual",
    "Swimwear", "Lingerie", "Pajamas", "Sportswear", "Formal",
    "Gimmick", "Tool", "Prefab", "Scene", "Pose",
]

# ── Tag Hierarchy ──────────────────────────────────
# parent → set of child tags. When a child is detected, the parent is auto-added.
TAG_HIERARCHY: dict[str, set[str]] = {
    "Outfit": {
        "Dress", "Skirt", "Pants", "Shorts", "Shirt", "Jacket",
        "Sweater", "Hoodie", "Vest", "Coat", "Tank Top", "Crop Top",
        "Maid", "School Uniform", "Military Uniform", "Kimono",
        "Yukata", "Swimsuit", "Lingerie", "Pajamas", "Sportswear",
        "Suit", "Casual", "Formal", "Gothic", "Lolita",
        "Cyberpunk", "Fantasy", "Idol Outfit",
    },
    "Accessory": {
        "Hat", "Glasses", "Mask", "Necklace", "Choker", "Earrings",
        "Bracelet", "Ring", "Brooch", "Bag", "Backpack",
        "Hair Accessory", "Ribbon", "Bow", "Collar",
        "Wings", "Tail", "Ears", "Horns", "Halo",
        "Weapon", "Shield", "Prop", "Tool", "Cape", "Scarf", "Belt",
    },
    "Hair": {
        "Hairstyle", "Bangs", "Ponytail", "Twin Tails", "Bob Cut",
        "Long Hair", "Short Hair", "Braids", "Drill Hair", "Ahoge",
    },
    "Body": {
        "Head", "Face", "Eyes", "Eyebrows", "Eyelashes",
        "Mouth", "Nose", "Hands", "Feet", "Arms", "Legs",
        "Skin", "Makeup", "Tattoo", "Scar", "Freckles",
        "Blush", "Lipstick", "Muscle", "Slim", "Chibi",
    },
    "Texture": {
        "Material", "Shader", "Normal Map", "Albedo", "Emission",
    },
    "Animation": {
        "Gesture", "Expression", "Emote", "Pose", "Dance",
    },
}

# ── Word → Tag Mapping ─────────────────────────────
# Lowercase tokens match to canonical tag names.
# Format: "word_or_substring": "Canonical Tag Name"
WORD_TO_TAG: dict[str, str] = {
    # ── Outfit / Clothing ──
    "outfit": "Outfit", "clothing": "Outfit", "clothes": "Outfit",
    "dress": "Dress", "ドレス": "Dress", "one-piece": "Dress", "onepiece": "Dress",
    "skirt": "Skirt", "スカート": "Skirt",
    "pants": "Pants", "パンツ": "Pants", "trousers": "Pants",
    "shorts": "Shorts", "ショーツ": "Shorts",
    "shirt": "Shirt", "シャツ": "Shirt", "blouse": "Shirt",
    "jacket": "Jacket", "ジャケット": "Jacket",
    "sweater": "Sweater", "セーター": "Sweater", "knit": "Sweater",
    "hoodie": "Hoodie", "パーカー": "Hoodie", "hoody": "Hoodie",
    "vest": "Vest", "ベスト": "Vest",
    "coat": "Coat", "コート": "Coat", "overcoat": "Coat",
    "tanktop": "Tank Top", "tank-top": "Tank Top", "タンクトップ": "Tank Top",
    "croptop": "Crop Top", "crop-top": "Crop Top",
    "maid": "Maid", "メイド": "Maid", "meido": "Maid",
    "school": "School Uniform", "uniform": "School Uniform",
    "制服": "School Uniform", "seifuku": "School Uniform",
    "military": "Military Uniform", "ミリタリー": "Military Uniform",
    "kimono": "Kimono", "着物": "Kimono",
    "yukata": "Yukata", "浴衣": "Yukata",
    "swimsuit": "Swimsuit", "swimwear": "Swimsuit", "bikini": "Swimsuit",
    "水着": "Swimsuit", "mizugi": "Swimsuit",
    "lingerie": "Lingerie", "ランジェリー": "Lingerie",
    "下着": "Lingerie", "underwear": "Lingerie", "bra": "Lingerie",
    "pajamas": "Pajamas", "pajama": "Pajamas", "パジャマ": "Pajamas",
    "sleepwear": "Pajamas",
    "sportswear": "Sportswear", "sport": "Sportswear", "athletic": "Sportswear",
    "suit": "Suit", "formal": "Formal", "スーツ": "Suit", "tuxedo": "Suit",
    "casual": "Casual", "カジュアル": "Casual",
    "gothic": "Gothic", "ゴシック": "Gothic", "goth": "Gothic",
    "lolita": "Lolita", "ロリータ": "Lolita", "loli": "Lolita",
    "cyberpunk": "Cyberpunk", "サイバー": "Cyberpunk", "cyber": "Cyberpunk",
    "fantasy": "Fantasy", "ファンタジー": "Fantasy",
    "idol": "Idol Outfit", "アイドル": "Idol Outfit",
    "costume": "Outfit", "cosplay": "Outfit", "衣装": "Outfit",
    "コーデ": "Outfit", "着せ替え": "Outfit", "setup": "Outfit",

    # ── Accessories ──
    "accessory": "Accessory", "accessories": "Accessory",
    "アクセサリー": "Accessory", "アクセ": "Accessory",
    "hat": "Hat", "帽子": "Hat", "cap": "Hat", "beanie": "Hat", "beret": "Hat",
    "glasses": "Glasses", "眼鏡": "Glasses", "megane": "Glasses",
    "sunglasses": "Glasses", "spectacles": "Glasses",
    "mask": "Mask", "マスク": "Mask",
    "necklace": "Necklace", "ネックレス": "Necklace", "pendant": "Necklace",
    "choker": "Choker", "チョーカー": "Choker",
    "earrings": "Earrings", "earring": "Earrings", "ピアス": "Earrings",
    "イヤリング": "Earrings", "piercing": "Earrings",
    "bracelet": "Bracelet", "ブレスレット": "Bracelet", "wristband": "Bracelet",
    "ring": "Ring", "リング": "Ring", "指輪": "Ring",
    "brooch": "Brooch", "ブローチ": "Brooch", "pin": "Brooch",
    "bag": "Bag", "バッグ": "Bag", "purse": "Bag", "handbag": "Bag",
    "backpack": "Backpack", "リュック": "Backpack",
    "hair-accessory": "Hair Accessory", "hairpin": "Hair Accessory",
    "hairclip": "Hair Accessory", "headband": "Hair Accessory",
    "髪飾り": "Hair Accessory", "ヘアピン": "Hair Accessory",
    "ribbon": "Ribbon", "リボン": "Ribbon",
    "bow": "Bow", "bowknot": "Bow", "リボン": "Ribbon",
    "collar": "Collar", "カラー": "Collar", "choker": "Choker",
    "wings": "Wings", "翼": "Wings", "羽根": "Wings", "羽": "Wings",
    "tail": "Tail", "尻尾": "Tail", "しっぽ": "Tail",
    "ears": "Ears", "耳": "Ears", "nekomimi": "Ears", "cat-ear": "Ears",
    "horns": "Horns", "角": "Horns", "ツノ": "Horns",
    "halo": "Halo", "光圈": "Halo", "angel-ring": "Halo",
    "weapon": "Weapon", "武器": "Weapon", "sword": "Weapon", "gun": "Weapon",
    "shield": "Shield", "盾": "Shield",
    "prop": "Prop", "小物": "Prop",
    "tool": "Tool", "道具": "Tool",
    "cape": "Cape", "マント": "Cape", "cloak": "Cape",
    "scarf": "Scarf", "マフラー": "Scarf", "スカーフ": "Scarf",
    "belt": "Belt", "ベルト": "Belt",

    # ── Hair ──
    "hair": "Hair", "髪": "Hair", "髪型": "Hair",
    "hairstyle": "Hairstyle", "hairdo": "Hairstyle",
    "bangs": "Bangs", "fringe": "Bangs", "前髪": "Bangs",
    "ponytail": "Ponytail", "ポニーテール": "Ponytail", "pony": "Ponytail",
    "twintails": "Twin Tails", "twin-tail": "Twin Tails",
    "ツインテール": "Twin Tails", "twintail": "Twin Tails",
    "bob": "Bob Cut", "bobcut": "Bob Cut", "ボブ": "Bob Cut",
    "long-hair": "Long Hair", "longhair": "Long Hair", "ロング": "Long Hair",
    "short-hair": "Short Hair", "shorthair": "Short Hair",
    "braids": "Braids", "braid": "Braids", "三つ編み": "Braids",
    "drill": "Drill Hair", "ドリル": "Drill Hair", "twin-drill": "Drill Hair",
    "ahoge": "Ahoge", "アホ毛": "Ahoge",

    # ── Body Parts ──
    "body": "Body", "身体": "Body", "ボディ": "Body", "torso": "Body",
    "head": "Head", "頭": "Head",
    "face": "Face", "顔": "Face",
    "eyes": "Eyes", "目": "Eyes", "eye": "Eyes",
    "eyebrows": "Eyebrows", "eyebrow": "Eyebrows", "眉": "Eyebrows", "眉毛": "Eyebrows",
    "eyelashes": "Eyelashes", "eyelash": "Eyelashes", "まつげ": "Eyelashes",
    "lash": "Eyelashes", "lashes": "Eyelashes",
    "mouth": "Mouth", "口": "Mouth", "lips": "Mouth",
    "nose": "Nose", "鼻": "Nose",
    "hands": "Hands", "hand": "Hands", "手": "Hands",
    "feet": "Feet", "foot": "Feet", "足": "Feet",
    "arms": "Arms", "arm": "Arms", "腕": "Arms",
    "legs": "Legs", "leg": "Legs", "脚": "Legs",
    "skin": "Skin", "肌": "Skin",
    "makeup": "Makeup", "メイク": "Makeup", "cosmetics": "Makeup",
    "tattoo": "Tattoo", "タトゥー": "Tattoo", "入れ墨": "Tattoo",
    "scar": "Scar", "傷跡": "Scar",
    "freckles": "Freckles", "freckle": "Freckles", "そばかす": "Freckles",
    "blush": "Blush", "チーク": "Blush", "赤面": "Blush",
    "lipstick": "Lipstick", "リップ": "Lipstick", "口紅": "Lipstick",
    "muscle": "Muscle", "muscular": "Muscle", "筋肉": "Muscle",
    "slim": "Slim", "スリム": "Slim", "thin": "Slim",
    "chibi": "Chibi", "ちび": "Chibi", "mini": "Chibi", "sd": "Chibi",

    # ── Texture / Material ──
    "texture": "Texture", "テクスチャ": "Texture", "tex": "Texture",
    "material": "Material", "マテリアル": "Material", "mat": "Material",
    "shader": "Shader", "シェーダー": "Shader",
    "normal-map": "Normal Map", "normalmap": "Normal Map", "normal": "Normal Map",
    "albedo": "Albedo",
    "emission": "Emission", "emissive": "Emission",
    "psd": "Texture", "png": "Texture",

    # ── Animation ──
    "animation": "Animation", "anim": "Animation",
    "アニメーション": "Animation",
    "gesture": "Gesture", "ジェスチャー": "Gesture",
    "expression": "Expression", "表情": "Expression",
    "emote": "Emote", "エモート": "Emote",
    "pose": "Pose", "ポーズ": "Pose",
    "dance": "Dance", "ダンス": "Dance",

    # ── Style / Species ──
    "kemono": "Kemono", "ケモノ": "Kemono", "獣人": "Kemono",
    "furry": "Furry", "fur": "Furry", "ケモノ": "Kemono",
    "neko": "Neko", "猫": "Neko", "cat": "Neko",
    "inumimi": "Inumimi", "犬耳": "Inumimi", "dog": "Inumimi",
    "kitsune": "Kitsune", "狐": "Kitsune", "fox": "Kitsune",
    "elf": "Elf", "エルフ": "Elf", "elves": "Elf",
    "oni": "Oni", "鬼": "Oni", "demon": "Oni",
    "angel": "Angel", "天使": "Angel",
    "vampire": "Vampire", "吸血鬼": "Vampire",
    "robot": "Robot", "ロボット": "Robot", "ロボ": "Robot",
    "mecha": "Robot", "android": "Robot",
    "doll": "Doll", "人形": "Doll",
    "wizard": "Wizard", "魔法使い": "Wizard", "mage": "Wizard",
    "knight": "Knight", "騎士": "Knight",
    "ninja": "Ninja", "忍者": "Ninja",
    "samurai": "Samurai", "侍": "Samurai",
    "japanese": "Japanese Style", "和風": "Japanese Style", "wa": "Japanese Style",
    "chinese": "Chinese Style", "中華": "Chinese Style",
    "western": "Western Style", "洋風": "Western Style",

    # ── Quality / Version ──
    "modified": "Modified", "改変": "Modified", "custom": "Custom",
    "update": "Update", "アップデート": "Update",
    "latest": "Latest", "最新": "Latest",
    "fix": "Fix", "修正": "Fix",
    "improved": "Improved", "改善": "Improved",
    "high-quality": "High Quality", "高品質": "High Quality",
    "realistic": "Realistic", "リアル": "Realistic",
    "kawaii": "Kawaii", "かわいい": "Kawaii", "cute": "Kawaii",
    "simple": "Simple", "シンプル": "Simple",

    # ── Additional common items ──
    "shoe": "Shoes", "shoes": "Shoes", "靴": "Shoes", "シューズ": "Shoes",
    "heel": "Heels", "heels": "Heels", "ハイヒール": "Heels",
    "boot": "Boots", "boots": "Boots", "ブーツ": "Boots",
    "sock": "Socks", "socks": "Socks", "靴下": "Socks", "ソックス": "Socks",
    "stocking": "Stockings", "stockings": "Stockings", "ストッキング": "Stockings",
    "glove": "Gloves", "gloves": "Gloves", "手袋": "Gloves",
    "tie": "Tie", "ネクタイ": "Tie", "necktie": "Tie",
    "watch": "Watch", "時計": "Watch",
    "umbrella": "Umbrella", "傘": "Umbrella",
    "guitar": "Prop", "マイク": "Prop", "mic": "Prop", "instrument": "Prop",
    "pet": "Pet", "ペット": "Pet",
    "whip": "Whip", "ムチ": "Whip",
    "chain": "Chain", "チェーン": "Chain",
    "flower": "Flower", "花": "Flower", "rose": "Flower",
    "jewel": "Jewelry", "jewelry": "Jewelry", "gem": "Jewelry",
    "heart": "Heart", "ハート": "Heart",
    "star": "Star", "星": "Star",
    "crown": "Crown", "王冠": "Crown",
    "cross": "Cross", "十字架": "Cross",
    "feather": "Feather", "羽根": "Wings",
    "fur": "Fur", "ファー": "Fur",
    "lace": "Lace", "レース": "Lace",
    "frill": "Frill", "フリル": "Frill",
    "leather": "Leather", "革": "Leather",
    "denim": "Denim", "デニム": "Denim",
    "silk": "Silk", "シルク": "Silk",
    "cotton": "Cotton",
    "velvet": "Velvet", "ベルベット": "Velvet",
    "transparent": "Transparent", "透明": "Transparent",
    "see-through": "Transparent", "sheer": "Transparent",
    "glow": "Glowing", "glowing": "Glowing", "発光": "Glowing",
    "sparkle": "Sparkle", "キラキラ": "Sparkle",

    # ── Extra avatar/model terms ──
    "base": "Avatar Base", "ベース": "Avatar Base",
    "avatar": "Avatar Base", "アバター": "Avatar Base",
    "prefab": "Prefab", "プレハブ": "Prefab",
    "scene": "Scene",
    "pose": "Pose",
    "gimmick": "Gimmick", "ギミック": "Gimmick",
    "ft": "Gimmick",  # face tracking
    "facetracking": "Gimmick", "facetrack": "Gimmick",
}

# ── Canonical genre names (single source of truth) ──
GENRE_NAMES: list[str] = ["Avatar Base", "Outfit & Acce", "Gimmick", "Tools"]

# ── All avatar names as a set for O(1) membership ──
ALL_AVATAR_NAMES: set[str] = set(TOP_AVATARS)

# ── Japanese → English (for filename detection) ──
JP_TO_EN: dict[str, str] = {
    "髪": "Hair", "髪型": "Hairstyle", "髪の毛": "Hair",
    "頭": "Head", "顔": "Face",
    "体": "Body", "身体": "Body", "ボディ": "Body",
    "手": "Hands", "腕": "Arms",
    "足": "Feet", "脚": "Legs",
    "耳": "Ears", "目": "Eyes",
    "口": "Mouth", "鼻": "Nose",
    "尾": "Tail", "尻尾": "Tail", "しっぽ": "Tail",
    "翼": "Wings", "羽根": "Wings", "羽": "Wings",
    "角": "Horns", "ツノ": "Horns",
    "服": "Outfit", "衣装": "Outfit", "コーデ": "Outfit",
    "セットアップ": "Outfit", "着せ替え": "Outfit",
    "アクセサリー": "Accessory", "アクセ": "Accessory",
    "靴": "Shoes", "シューズ": "Shoes",
    "下着": "Lingerie", "パンツ": "Pants",
    "スカート": "Skirt", "ドレス": "Dress",
    "ジャケット": "Jacket", "シャツ": "Shirt",
    "セーター": "Sweater", "パーカー": "Hoodie",
    "水着": "Swimwear", "着物": "Kimono", "浴衣": "Yukata",
    "制服": "Uniform", "メイド": "Maid",
    "猫耳": "Nekomimi", "猫": "Neko",
    "犬耳": "Inumimi", "狐": "Kitsune", "耳": "Ears",
    "アバター": "Avatar Base", "アバター改変": "Avatar Base",
    "テクスチャ": "Texture", "テクスチャー": "Texture",
    "マテリアル": "Material",
    "シェーダー": "Shader",
    "プレハブ": "Prefab",
    "アニメーション": "Animation",
    "ジェスチャー": "Gesture", "エモート": "Emote",
    "ポーズ": "Pose",
    "改変": "Modified", "カスタム": "Custom",
    "最新": "Latest", "アップデート": "Update",
    "修正": "Fix", "改善": "Improved",
    "高品質": "High Quality", "リアル": "Realistic",
    "かわいい": "Kawaii", "シンプル": "Simple",
    "ゴシック": "Gothic", "ロリータ": "Lolita",
    "サイバー": "Cyberpunk", "ミリタリー": "Military",
    "ファンタジー": "Fantasy", "和風": "Japanese Style",
    "中華": "Chinese Style", "洋風": "Western Style",
    "原形": "Avatar Base", "素体": "Avatar Base",
    "フィギュア": "Figure", "人形": "Doll",
    "ロボ": "Robot", "ロボット": "Robot",
    "獣人": "Kemono", "ケモノ": "Kemono",
    "エルフ": "Elf", "鬼": "Oni", "悪魔": "Demon",
    "天使": "Angel", "吸血鬼": "Vampire",
    "魔法使い": "Wizard", "騎士": "Knight",
    "忍者": "Ninja", "侍": "Samurai",
    "アイドル": "Idol Outfit", "アイドル衣装": "Idol Outfit",
}
